### ISSUE TITLE
Can't use on windows: character `*` is invalid in file names

### ISSUE THREAD

**Issue by mattn** [aperezdc/vim-template#54] opened 2015-01-06 04:28 UTC
![](http://go-gyazo.appspot.com/86c5784f175ddaff.png)

**Comment by aperezdc** [comment] 2015-01-06 11:50
This is caused by the fact that the `*` character is invalid in file Windows file systems. We have some [support to change the characters which are used as wildcards](https://github.com/aperezdc/vim-template/issues/38#issuecomment-51549928) but you will still need to rename the built-in templates yourself — probably your best solution for the moment is to download a `.zip` from GitHub and rename the files when extracting. Also, we may be moving the built-in templates to a Git submodule, so Windows users can just skip checking them out.

**Comment by muff1nman** [comment] 2015-01-10 19:52
Would you mind trying this version of vim-template https://github.com/muff1nman/vim-template/tree/windows-path-fix?

**Comment by muff1nman** [comment] 2015-01-25 23:48
ping @mattn

**Comment by mattn** [comment] 2015-01-25 23:54
Sorry, I didn't use this plugin. But just to notice the issue.

**Comment by muff1nman** [comment] 2015-02-28 22:43
Resolved via #57

**Closed by muff1nman** 2015-02-28 22:43 UTC
Labels: bug
