### ISSUE TITLE
Problem with expanding wildcards.

### ISSUE THREAD

**Issue by straywarrior** [aperezdc/vim-template#92] opened 2015-12-01 14:33 UTC
I installed vim-template on both OS X and Ubuntu and my Vim version is 7.4.
However, Vim cannot find the template files.
I find that the command "find -L ..." cannot be executed correctly in Vim:
<img width="1609" alt="2015-12-01 22 25 57" src="https://cloud.githubusercontent.com/assets/6890059/11503341/01633d90-987b-11e5-83e8-bf086142b2ba.png">
But this command is working well in my shell, so it might be Vim's problem.

So, I modify the templates.vim to disable the use of "find" and now it works temporarily.
Is there something wrong with my Vim? I think there should be another way to solve this problem.

Thank you.

**Comment by aperezdc** [comment] 2015-12-01 21:06
In you screenshot it seems that you are trying to use Vim's `:find` (an Ex command), which does not have any to do with the invocation of `find` program from the system. That being said, I do not know why the plugin is not behaving correctly for you. Would you mind executing the following from Vim and writing back the result?:

```vim
:echo glob("`find -L '/Users/straywarrior/Documents/Developers/practice/network_programming/' -maxdepth 1 -type f -name '.vim-template:*'`")
```

**Comment by straywarrior** [comment] 2015-12-02 01:28
Thank you.
I execute the ":echo glob(...)" in Vim but there's nothing printed...
I'm sure there are sample templates in ~/.vim/bundle/vim-template/templates/.  I try to execute something like this in Vim but there is no result returned either. (The results in Ubuntu and OS X have no difference.) 
```
:echo glob("`find -L '/home/fzt/.vim/bundle/vim-template/templates/' -maxdepth 1 -type f -name '=template=*'`")
```

**Comment by muff1nman** [comment] 2015-12-13 01:26
Hmm. I'll try to get a hold of a macbook in the next couple days to see if I can reproduce.

**Comment by aperezdc** [comment] 2015-12-13 22:24
@muff1nman: that would be awesome, I don't have an easy way of getting access to a MacOS X machine right now and I cannot investigate this further. Thanks a lot for offering to look into the issue :)

**Comment by muff1nman** [comment] 2015-12-15 03:18
vim-template seems to work fine on a near default install of Mac OSX - I installed the developer tools to use git. Are you also having this issue with Ubuntu? Can you please add `let g:templates_debug=1` to your `.vimrc` and then post the results of editing a file with logging enabled? e.g. `vim -V9vim-template.log test.txt`. What variables do you have set in your vimrc?

**Comment by straywarrior** [comment] 2015-12-15 16:00
I meet the problem both in Ubuntu and OS X.
But I just found something that may help. I added a set to vimrc:
```
set shell=/bin/bash
```
And then my vim-template works well.
I usually use fish shell and I know there are some differences between fish and bash. However, the command below can be executed correctly in fish. 
```
find -L '/home/fzt/.vim/bundle/vim-template/templates/' -maxdepth 1 -type f -name '=template=*'
```
So I don't know the exact reason why vim-template cannot work without setting shell to bash.

Thank you all.

**Comment by aperezdc** [comment] 2015-12-15 16:48
@straywarrior: That is very interesting, but I have installed `fish` in my machine, and I cannot reproduce the issue by adding this in my `~/.vimrc`:

```vim
set shell=/bin/fish
```

but I cannot reproduce the issue either. I have also tried running Vim from inside `fish` and overwriting the `SHELL` environment variable, like this:

```sh
hikary ~ % fish  # Inside Zsh, this starts Fish
aperez@hikari ~> export SHELL=/bin/fish  # Inside Fish, set variable
aperez@hikari ~> vim foo.c  # Still inside Fish, try to create a new file with Vim
```

but still I cannot reproduce the issue.

Here I have Fish version 2.2.0 with its default configuration. Which version of `fish` are you using? Do you have changed any options which may affect shell expansion and/or globbing?

**Comment by dbellavista** [comment] 2016-01-20 11:23
I have the same problem with fish. And I can reproduce on Mac osx (default shell `fish`)

```
daniele ~> bash # inside fish, start bash
bash$ export SHELL=/bin/bash
bash$ vim
```

Executing ```:echo glob("`find . -print -maxdepth 1`")``` shows the file list.

**Comment by aperezdc** [comment] 2017-06-22 11:21
@dbellavista @straywarrior Can any of you confirm that you got the plug-in working when using Fish as well? Or is the bug still there for you?

**Comment by dbellavista** [comment] 2017-06-22 11:31
@aperezdc works for me with `fish` shell. Ty

**Comment by aperezdc** [comment] 2017-06-22 11:39
Thanks for the confirmation @dbellavista! Let's close this issue now — it can be reopened if needed later on.

**Closed by aperezdc** 2017-06-22 11:39 UTC
Labels: bug, needs info
